---
title: "doe4: Multidimensional Scaling"
author: "Hao Zhong"
date: "3/26/2017"
output:
  html_notebook: default
  html_document: default
  pdf_document: default
---


```{r echo=FALSE, eval=FALSE}
setwd("/Users/Hao/Projects/RPI-DARPA-DS/")
```

```{r results='hide', eval=FALSE, echo=FALSE}
install.packages("randomForest")
install.packages("e1071")
install.packages("ggplot2")
install.packages("GGally")
install.packages("reshape2")
install.packages("kernlab")
install.packages("caret") # confusionMatrix
```

```{r echo=FALSE, eval=TRUE}
mydata <- read.csv("Fake Data DOE_IV 1_24_2017.csv", header = TRUE, stringsAsFactors = FALSE)
```

```{r echo=FALSE}
# Categorical and numerical variables
independent.variables.cat <- c("Surface.Preparation", "Contaminate.Type")
independent.variables.num <- c("Adhesive.Out.Time", "Prep..to.Bond.Time", "Contamination.Amount")
# All 5 variables
independent.variables.all <- c(independent.variables.cat, independent.variables.num)
```

```{r warning=FALSE,  echo=FALSE}
# Correct data types
mydata$Adhesive.Out.Time <- as.numeric(mydata$Adhesive.Out.Time)
mydata$Prep..to.Bond.Time <- as.numeric(mydata$Prep..to.Bond.Time)
mydata$Surface.Preperation <- as.factor(mydata$Surface.Preperation)
mydata$Contaminate.Type <- as.factor(mydata$Contaminate.Type)
mydata$Contamination.Amount <- as.numeric(mydata$Contamination.Amount)
# Gic -> y = 'LowGic' or 'HighGic'
mydata$y <- as.factor(ifelse(mydata$Gic < 5, 'LowGic', 'HighGic'))
# Omit NA's
mydata <- na.omit(mydata)
# (*) FIX weird negative values observed in Prep..to.Bond.Time
mydata$Prep..to.Bond.Time <- abs(mydata$Prep..to.Bond.Time)
# Add a duplicate column of Surface.Preperation with correct column name
mydata$Surface.Preparation <- mydata$Surface.Preperation
```


```{r}
# Classical MDS
# 
library(stats)
library(MASS)
library(ggplot2)
# 
# Variable "data" stores the data to be used in this process, so that user
#   does not need to go in the codes to change dataset names everywhere.
data <- mydata    
# Variable data.mat stores only the variables we are looking at.
#   Note that it might be good to look at data subsetted by different ranges of
#     Adhesive.Out.Time or Prep..to.Bond.Time
#   Also, seems AOT and PBT are in different unit, which causes huge scale
#     difference in their numerical values. Since this MDS is based by a
#     calculated distance matrix (see codes), and this calculation is likely to
#     be distorted by the this difference in scale.
# 
# Create a matrix with only the variables concerned.
# data.mat <- as.matrix(data[, c("Adhesive.Out.Time", "Prep..to.Bond.Time", "Contamination.Amount", "Gic")])
# Calculate a difference matrix. Default metric is euclidean
# data.dist <- dist(data.mat, diag = TRUE, method = "euclidean")
data.dist <- dist(data[, c("Adhesive.Out.Time", "Prep..to.Bond.Time", "Contamination.Amount", "Gic")], diag = FALSE, method = "euclidean")

# cmdscale
mds <- cmdscale(data.dist, k = 2) 
# Plot MDS and color points by Contaminate.Type, Surface.Preparation, and y
ggplot() + geom_jitter(aes(x = mds[, 1], y = mds[, 2], col = data$Contaminate.Type))
ggplot() + geom_jitter(aes(x = mds[, 1], y = mds[, 2], col = data$Surface.Preparation))
ggplot() + geom_jitter(aes(x = mds[, 1], y = mds[, 2], col = data$y))

# isoMDS
mds <- isoMDS(data.dist, k = 2) 
# Plot MDS and color points by Contaminate.Type, Surface.Preparation, and y
ggplot() + geom_jitter(aes(x = mds$points[, 1], y = mds$points[, 2], col = data$Contaminate.Type))
ggplot() + geom_jitter(aes(x = mds$points[, 1], y = mds$points[, 2], col = data$Surface.Preparation))
ggplot() + geom_jitter(aes(x = mds$points[, 1], y = mds$points[, 2], col = data$y))
```

